# Project information

## START: Django
docs_dir: 'mkdocs'
site_dir: 'docs/static/mkdocs_build'
## END: Django

site_name: MkDocs Luiz
site_description: Documentação Pessoal de Luiz Fernando
site_author: Luiz Fernando dos Santos Daniel
site_url: https://luizddaniel.github.io/

# Repository
repo_name: luizddaniel/django_material
repo_url: https://github.com/luizddaniel/django_material
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 Luiz Fernando dos S. Daniel'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: false

  # Default values, taken from mkdocs_theme.yml
  language: pt
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Customization
extra:
  social:
    - type: globe
      link: https://luizddaniel.github.io
    - type: github-alt
      link: https://github.com/luizddaniel
    - type: linkedin
      link: https://linkedin.com/in/luiz-fernando-d-2a290747/ target="_blank"
    
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
pages:

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
